export const Languages = {
    uz: {
        allstations: "Barcha Stantsiyalar",
        distance: "Masofa",
        origin: "Ishlab chiqarish",
        available: "Hozir mavjud",
        notAvailable: "Mavjud emas",
        contacts: "Aloqa",	
        openFrom: "Ochilish vaqti",
        price: "Narx",
        showOnMap: "Kartada ko'rsatish",
        locationPermission: "Geolokatsiyani kuzatish",
        nearestGasStations: "Eng yaqin AЗС",
        filters: "Filtrlar",
        openInMaps: "Stansiyaga borish",
        noDistanceMsg: "Masofa ko'rsatilmagan",
        cheapestGasStations: "Yoqilg'i - ",
        cheapestByType: "Turi bo'yicha arzon"
    },
    ru: {
        allstations: "Все Заправки",
        distance: "Растояние",
        origin: "Производство",
        available: "Сейчас доступен",
        notAvailable: "Нет в наличии",
        contacts: "Контакты",
        openFrom: "Время работы",
        price: "Цена",
        showOnMap: "Показать на карте",
        locationPermission : "Отслеживать геолокацию",
        nearestGasStations: "Ближайшие AЗС",
        filters: "Фильтры",
        openInMaps: "Поехать на станцию",
        noDistanceMsg: "Расстояние не указано",
        cheapestGasStations: "Топливо - ",
        cheapestByType: "Дешевые по типу топлива"
    },
    en: {
        allstations: "All Stations",
        distance: "Distance",
        origin: "Origin",
        available: "Available",
        notAvailable: "Not Available",
        contacts: "Contacts",
        openFrom: "Open from",
        price: "Price",
        showOnMap: "Show on Map",
        locationPermission: "Track Location",
        nearestGasStations: "Nearest Gas Stations",
        filters: "Filters",
        openInMaps: "Open in Maps",
        noDistanceMsg: "Distance not specified",
        cheapestGasStations: "Fuel - ",
        cheapestByType: "Cheapest by fuel type"
    },
};

