export const Languages = {
    uz: {
        allstations: "Barcha Stantsiyalar",
        distance: "Masofa",
        origin: "Ishlab chiqarish",
        available: "Hozir mavjud",
        notAvailable: "Mavjud emas",
        contacts: "Aloqa",	
        openFrom: "Ochilish vaqti",
        price: "Narx",
        showOnMap: "Kartada ko'rsatish",
        locationPermission: "Geolokatsiyani kuzatish",
        nearestGasStations: "Eng yaqin AЗС",
        filters: "Filtrlar",
        openInMaps: "Stansiyaga borish",
    },
    ru: {
        allstations: "Все Заправки",
        distance: "Растояние",
        origin: "Производство",
        available: "Сейчас доступен",
        notAvailable: "Нет в наличии",
        contacts: "Контакты",
        openFrom: "Время работы",
        price: "Цена",
        showOnMap: "Показать на карте",
        locationPermission : "Отслеживать геолокацию",
        nearestGasStations: "Ближайшие AЗС",
        filters: "Фильтры",
        openInMaps: "Поехать на станцию",
    },
    en: {
        allstations: "All Stations",
        distance: "Distance",
        origin: "Origin",
        available: "Available",
        notAvailable: "Not Available",
        contacts: "Contacts",
        openFrom: "Open from",
        price: "Price",
        showOnMap: "Show on Map",
        locationPermission: "Track Location",
        nearestGasStations: "Nearest Gas Stations",
        filters: "Filters",
        openInMaps: "Open in Maps",
    },
};

